function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(10)=1;
    params(5)=1/(1+params(6));
    params(11)=params(4);
    params(12)=params(10)-params(6)*params(4)/(1+params(6));
    params(15)=params(8)/(1-params(8))*(params(12)/params(3))^params(9);
    params(13)=params(10)-params(12);
    params(14)=0;
    ys_(1)=log(params(10));
    ys_(3)=params(11);
    ys_(2)=log(params(12));
    ys_(6)=log(params(15));
    ys_(4)=params(13);
    ys_(5)=params(14);
    % Auxiliary equations
end
