function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(11)=1;
    params(6)=1/(1+params(7));
    params(12)=params(5);
    params(13)=params(11)-params(7)*params(5)/(1+params(7));
    params(16)=params(9)/(1-params(9))*(params(13)/params(4))^params(10);
    params(14)=params(11)-params(13);
    params(15)=0;
    ys_(1)=log(params(11));
    ys_(3)=params(12);
    ys_(2)=log(params(13));
    ys_(6)=log(params(16));
    ys_(4)=params(14);
    ys_(5)=params(15);
    % Auxiliary equations
ys_(7)=ys_(1);
end
